version: "3.5"

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wpd:
    driver: local
    name: wpd
    driver_opts:
      type: none
      o: bind
      device: /home/jkaczmar/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/jkaczmar/data/mariadb

services:
  mariadb:
    container_name: mariadb
    build: ./requiremenents/mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requiremenents/wordpress
    depends_on:
      - mariadb
    volumes:
      - wpd:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: ./requiremenents/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wpd:/var/www/html
    networks:
      - inception
    restart: unless-stopped

